# This is a basic workflow to help you get started with Actions

name: Deploying react

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

     # Now we will specify the version and install nodeJS 
    - name: Installing node js on server machine # this could be a name of your command just for memorizing peupose and need of that command
      uses: actions/setup-node@v2-beta #this would be tha actual command that will run on your server (ubuntu-github)
      with:
        node-version : 12
